name: bootcamprojeai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  http: 1.2.1
  google_generative_ai: ^0.4.3
  flutter_gemini: ^2.0.3
  shared_preferences: ^2.0.6
  weather_icons: ^3.0.0
  firebase_core: ^2.5.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_svg: ^0.22.0
  cloud_firestore: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_image.png
    - assets/icons/google_logo.svg
    - assets/icon/app_icon.png
